ALTER TABLE "Creator"
ADD COLUMN IF NOT EXISTS "acceptedPaymentAssets" TEXT[] NOT NULL DEFAULT ARRAY['ALEO_CREDITS']::TEXT[];

ALTER TABLE "Creator"
ADD COLUMN IF NOT EXISTS "acceptedPaymentVisibilities" TEXT[] NOT NULL DEFAULT ARRAY['PUBLIC', 'PRIVATE']::TEXT[];
