ALTER TABLE "Content"
ADD COLUMN IF NOT EXISTS "encryptedData" TEXT;

ALTER TABLE "Content"
ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);

ALTER TABLE "Content"
ADD COLUMN IF NOT EXISTS "viewLimit" INTEGER;

ALTER TABLE "Content"
ADD COLUMN IF NOT EXISTS "views" INTEGER NOT NULL DEFAULT 0;
